config/routes.rb
Rails.application.routes.draw do
  root "forum_threads#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forum_threads, only: [:show, :new, :create] do
    resources :forum_posts, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread, counter_cache: true

  validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
  has_many :forum_posts

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @thread = ForumThread.find(params[:forum_thread_id])
    @post = ForumPost.new(resource_params)

    @post.forum_thread = @thread
    @post.user = current_user
    if @post.save
      redirect_to forum_thread_path(@thread)
    else
      render 'forum_threads/show'
    end
  end

  private

  def resource_params
    params.require(:forum_post).permit(:content)
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @threads = ForumThread.order(id: :desc)
  end

  def show
    @thread = ForumThread.find(params[:id])
    @post = ForumPost.new
  end

  def new
    @thread = ForumThread.new
  end

  def create
    @thread = ForumThread.new(resource_params)
    @thread.user = current_user
    if @thread.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def resource_params
    params.require(:forum_thread).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # for notice alert bootstrap 4
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/views/forum_threads/index.html.erb
<div class="welcome-msg">
  <div class="row mb-3">
    <div class="col-md-9">
      <h1>Welcome to dotForum!</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>
    <% if user_signed_in? %>
    <div class="col-md-3 my-auto">
      <%= link_to 'Buat Thread', new_forum_thread_path, class: 'btn btn-primary btn-md btn-block' %>
    </div>
    <% end %>
  </div>
</div>
<% @threads.each do |thread| %>
  <div class="threads card card-body my-2">
    <h3><%= link_to thread.title, forum_thread_path(thread), class: 'text-decoration-none text-dark'  %></h3>
    <span class="meta"><small><%= I18n.l thread.created_at.to_date %> oleh <%= thread.user.name %></small></span>
    <hr>
    <p><%= truncate thread.content, length: 250 %></p>
    <span><%= thread.forum_posts_count %> obrolan</span>
  </div>
<% end %>

app/views/forum_threads/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>Buat Thread Baru</h1>
  </div>
  <div class="card-body">
    <%= form_for @thread do |f| %>
      <div class="forum-group mb-3">
        <%= f.label :title, 'Masukkan judul thread:' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="forum-group mb-3">
        <%= f.label :content, 'Apa yang ingin kamu bahas:' %>
        <%= f.text_area :content, class: 'form-control', rows: 10 %>
      </div>
      <% if @thread.errors.any? %>
      <div class="notice">
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <% @thread.errors.full_messages.each do |error| %>
          <%= error %><br>
        <% end %>
        </div>
      </div>
      <% end %>
      <div class="forum-group">
        <%= f.submit 'Publish', class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/forum_threads/show.html.erb
<div class="thread-detail card card-body my-2">
  <h1><%= @thread.title %></h1>
  <span class="meta"><small><%= I18n.l @thread.created_at.to_date %> oleh <%= @thread.user.name %></small></span>
  <p><%= truncate @thread.content, length: 250 %></p>
</div>
<div class="comment">
  <h3 class="ml-3 ml-md-3">Komentar</h3>
  <% if @thread.forum_posts.any? %>
    <% @thread.forum_posts.each do |post| %>
      <div class="comment-list card card-body my-3">
        <div class="row">
          <div class="col-md-2">
            <%= image_tag 'profile-placeholder.png', class: 'img-fluid rounded' %>
          </div>
          <div class="col-md-3 mt-2 mt-md-0 border-right">
            <b><%= post.user.name %></b><br>
            <span><small><%= I18n.l post.created_at.to_date %></small></span>
          </div>
          <div class="col-md-7 pl-md-5">
            <p><%= post.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <% if user_signed_in? %>
      <p class="ml-md-3">Jadilah yang pertama berkomentar.</p>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%= form_for [@thread, @post] do |f| %>
      <div class="comment-form">
        <div class="forum-group mb-3">
          <%= f.label :content, 'Berikan tanggapanmu :', class: 'ml-3 ml-md-3' %>
          <%= f.text_area :content, class: 'form-control', rows: 6 %>
        </div>
        <% if @post.errors.any? %>
          <div class="notice">
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <% @post.errors.full_messages.each do |error| %>
                <%= error %><br>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="forum-group">
          <%= f.submit 'Publish Komentar', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="mt-4 text-center">Kamu perlu login untuk dapat berkomentar.</p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <b><%= link_to 'DOTFORUM', root_path, class:'navbar-brand' %></b>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Beranda', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Tentang Forum', nil, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Cari judul thread" aria-label="Cari">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Cari</button>
    </form>
    <ul class="navbar-nav ml-2">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= user_signed_in? ? current_user.name : 'Hi, mas Bro!' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% unless user_signed_in? %>
            <%= link_to 'Daftar', new_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Login', new_user_session_path, class: 'dropdown-item' %>
          <% else %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DotForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-5 pt-2">
      <div class="row my-3">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <%= flash_messages %>
          <%= yield %>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </body>
</html>